# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='news',
        ),
    ]
