# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='check',
            new_name='big',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='detailed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
